use sakila;

-- 1. List the number of films per category.
select * from film;
select * from film_category;
select * from category;

select fc.category_id, count(*) as `number_of_films`
  from film as f
  join film_category as fc
  on f.film_id=fc.film_id group by fc.category_id; -- join on film id, group by caegory and use agg count(*)

select c.name, fc.category_id, count(*) as `number_of_films`
  from film as f
  join film_category as fc
  on f.film_id=fc.film_id 
  join category as c
  on fc.category_id=c.category_id
  group by fc.category_id order by category_id asc;
  
-- 2, Retrieve the store ID, city, and country for each store.
select * from store;
select * from address; -- join by address_id, it has address and city_id
select * from country;
select * from city;

select 
  s.store_id,
  c.city,
  co.country
from store as s
join address as a
on s.address_id=a.address_id
join city as c
on a.city_id=c.city_id
join country co
on c.country_id=co.country_id;

-- 3. Calculate the total revenue generated by each store in dollars.
select * from payment; -- sum(amount)
select * from store; -- group by store_id

select s.store_id, sum(p.amount) as `total_revenue`
  from store as s
  join payment as p
  on s.manager_staff_id=p.staff_id 
  group by s.store_id;

-- 4. Determine the average running time of films for each category.
select * from film;
select * from film_category;
select * from category;

select 
    c.name,
    fc.category_id,
    round(avg(f.length)) as `avg length in min`
  from film as f
  join film_category as fc
  on f.film_id=fc.film_id
  join category as c
  on fc.category_id=c.category_id
  group by  fc.category_id order by round(avg(f.length)) desc;
